# Generated by Django 2.2.9 on 2020-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcat',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50)),
                ('caticonnm', models.CharField(max_length=1000)),
            ],
        ),
    ]
