# Generated by Django 2.2.9 on 2020-01-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('file1', models.CharField(max_length=500)),
                ('file2', models.CharField(max_length=500)),
                ('file3', models.CharField(max_length=500)),
                ('file4', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
