# Generated by Django 2.2.9 on 2020-01-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
