# Generated by Django 2.2.9 on 2020-01-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_location_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('locationid', models.IntegerField()),
                ('uid', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=100)),
            ],
        ),
    ]
